### ISSUE TITLE
RESOLVED: ON/OFF Doesn't work

### ISSUE THREAD

**Issue by cisco92** [jchnlemon/homebridge-telldus#17] opened 2016-09-13 14:12 UTC
Hi,

I use the homebridge-telldus plugin for homebridge, it does get my devices from telldus live but when I try to change the state of the device, nothing happends. 

My config.json is as such:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "accessories": [
    ],

    "platforms": [
        {
            "platform" : "Telldus",
            "name" : "Telldus Liv!e",
            "public_key" : "secret",
            "private_key" : "secret",
            "token" : "secret",
            "token_secret" : "secret"
        }
    ]
}
```

When I use the "Eve" app on iOS (I have tried several but with the same result), in the terminal I get `[9/13/2016, 4:01:14 PM] [Telldus Liv!e] [Giraff] Executing command bool : 1` and then nothing happens. In one app the `1` was changed to `true` but that didn't make a difference. And after that I get an error in the app saying `HomeKit reported a communication failure. Please try again.`

Anyone know a solution?

**Comment by steam0** [comment] 2016-09-13 14:15
THis is a duplicate of [this issue](https://github.com/jchnlemon/homebridge-telldus/issues/16)

**Comment by cisco92** [comment] 2016-09-13 14:29
Resolved.
Removed index.js and replaced it with [index.js](https://raw.githubusercontent.com/mansica/homebridge-telldus/456e91548b0a410da7c2034a63fc3210f9f2f6a7/index.js) and it works without any problems!

**Comment by steam0** [comment] 2016-09-13 14:30
What is the difference between these index.js-files? @cisco92

**Comment by cisco92** [comment] 2016-09-13 14:31
They look totally different.. I just looked at a swedish Telldus forum and they all used with index.js instead of the original one.. Works with all devices it seems like. Just try it out.. Keep the original for backup.

**Comment by steam0** [comment] 2016-09-13 14:32
Maybe you should add a pull request for that index.js if this solves everyones problem?

**Comment by cisco92** [comment] 2016-09-13 14:37
Yeah but I created my github account today.. So don't even know how to create a pull request.. xD

**Comment by steam0** [comment] 2016-09-13 14:37
Meh, nvm I just did it.

**Comment by steam0** [comment] 2016-09-13 14:38
Do you mind linking the webforum to me?

**Comment by cisco92** [comment] 2016-09-13 14:39
https://github.com/mansica/homebridge-telldus

**Comment by steam0** [comment] 2016-09-13 14:43
Seems like he has already tried to add this as a pull request. Case closed and thank you.

**Comment by cisco92** [comment] 2016-09-13 14:45
Did you try the replacement index.js to see if it worked??

**Comment by steam0** [comment] 2016-09-13 14:45
It worked like a charm. :)

**Comment by ehenrik** [comment] 2016-10-04 20:14
I spent an evening applying these changes manually and can confirm that these changes work! Great job. It would however be awfully nice to get them packaged in a npm package since the fix has some dependencies etc. that have to be manually installed.

**Comment by steam0** [comment] 2016-10-04 20:38
We have tried. This dude just wont accept the pull request! 🙄

**Comment by jchnlemon** [comment] 2016-10-04 21:27
Hi and sorry for the _really_ late response, haven't had time to work on this at all for a couple of months... It will be changed from now on :)

I've merged the pull request now anyways. Please confirm if it works and I'll close this.

**Comment by steam0** [comment] 2016-10-06 07:01
Do you mind adding some of us as administrators to this project? I dont min answering questions and approving working pull requests.

I am the sole user in the homebridge-telldus channel on the official homebridge slack. Please do pop in if you want to.

**Comment by steam0** [comment] 2016-10-08 09:09
Verified by issue #16

**Closed by steam0** 2016-10-08 09:09 UTC
